# Generated by Django 4.2.2 on 2023-07-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Customer_Email', models.CharField(max_length=50)),
                ('Customer_Password', models.CharField(max_length=255)),
                ('Customer_Confirm_Password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Info',
            fields=[
                ('Phone_Number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Facebook', models.CharField(max_length=30)),
                ('Twitter', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=6)),
            ],
        ),
    ]
