# Generated by Django 4.2.3 on 2023-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customer_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('image', models.ImageField(default=None, null=True, upload_to='uploads')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
