# Generated by Django 4.2.2 on 2023-10-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_admin_blogpost_cart_order_payment_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_image',
            field=models.ImageField(default=None, null=True, upload_to='uploads'),
        ),
    ]
