# Generated by Django 4.2.2 on 2023-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='message_posted',
            field=models.DateField(null=True),
        ),
    ]
