# Generated by Django 4.2.2 on 2023-11-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_cart_order_id_payment_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
